export const PRODUCT_LIST_REQUEST_START = "PRODUCT_LIST_REQUEST_START"
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS"
export const PRODUCT_LIST_REQUEST_FAILURE = "PRODUCT_LIST_REQUEST_FAILURE"

export const SINGLE_PRODUCT_REQUEST_START = "SINGLE_PRODUCT_REQUEST_START"
export const SINGLE_PRODUCT_REQUEST_SUCCESS = "SINGLE_PRODUCT_REQUEST_SUCCESS"
export const SINGLE_PRODUCT_REQUEST_FAILURE = "SINGLE_PRODUCT_REQUEST_FAILURE"
