export const PRODUCT_LIST_REQUEST_START = "PRODUCT_LIST_REQUEST_START"
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS"
export const PRODUCT_LIST_REQUEST_FAILURET = "PRODUCT_LIST_REQUEST_FAILURET"
